# Generated by Django 4.2.7 on 2025-12-02 16:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Начало периода видимости')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Конец периода видимости')),
                ('is_selection_closed', models.BooleanField(default=False, verbose_name='Выбор закрыт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Группа товаров',
                'verbose_name_plural': 'Группы товаров',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='daily_balance_amount',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10, verbose_name='Начисление в рабочий день'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Учётная запись подтверждена'),
        ),
        migrations.AddField(
            model_name='employee',
            name='min_balance_limit',
            field=models.DecimalField(decimal_places=2, default=-1000, max_digits=10, verbose_name='Минимальный баланс (блокировка)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='MenuItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu_items/%Y/%m/%d/', verbose_name='Изображение')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.menuitem', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ['-is_primary', 'order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.menuitemgroup', verbose_name='Группа'),
        ),
    ]
