# Generated by Django 4.2.7 on 2025-12-02 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_menuitemgroup_employee_daily_balance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.menuitemgroup', verbose_name='Группа товаров'),
        ),
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('accrual', 'Начисление'), ('deduction', 'Списание'), ('correction', 'Корректировка'), ('refund', 'Возврат')], max_length=20, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс после операции')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to='orders.employee', verbose_name='Сотрудник')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_transactions', to='orders.order', verbose_name='Связанный заказ')),
            ],
            options={
                'verbose_name': 'Операция с балансом',
                'verbose_name_plural': 'Операции с балансом',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkDayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('day_type', models.CharField(choices=[('work', 'Рабочий день'), ('vacation', 'Отпуск'), ('sick_leave', 'Больничный'), ('day_off', 'Отгул'), ('holiday', 'Праздничный день')], default='work', max_length=20, verbose_name='Тип дня')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_calendar', to='orders.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Календарь рабочих дней',
                'verbose_name_plural': 'Календарь рабочих дней',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
