# Generated by Django 4.2.7 on 2025-12-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_group_balancetransaction_workdaycalendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('reserved', 'Зарезервирован'), ('confirmed', 'Подтвержден'), ('sent', 'Отправлен в ресторан'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
