# Generated by Django 4.2.7 on 2025-12-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employee',
            name='login_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль для входа (хэш)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='login_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Логин для входа'),
        ),
    ]
