# Generated by Django 4.2.7 on 2025-12-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_employee_options_remove_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.IntegerField(blank=True, null=True, verbose_name='Калорийность (ккал)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Углеводы'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='composition',
            field=models.TextField(blank=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Жиры'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Белки'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на источник'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='weight',
            field=models.CharField(blank=True, max_length=50, verbose_name='Вес/Объем'),
        ),
    ]
