# Generated by Django 4.2.7 on 2025-12-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_systemconfig_menuitemgroup_is_selection_closed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('day_type', models.CharField(choices=[('work', 'Рабочий день'), ('holiday', 'Выходной/Праздник')], default='work', max_length=20, verbose_name='Тип дня')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Рабочий день (общий)',
                'verbose_name_plural': 'Рабочие дни (общий календарь)',
                'ordering': ['-date'],
            },
        ),
    ]
